<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Car;
use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = Brand::pluck('id', 'slug');
        $categories = Category::pluck('id', 'name_en');
        $myCars = [
            [
                'brand_id' => $brands['toyota'],
                'category_id' => $categories['Popular'],
                'model_en' => 'Camry',
                'model_ar' => 'كامري',
                'image' => 'assets/images/site/cars/toyota_camry.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['ford'],
                'category_id' => $categories['VIP'],
                'model_en' => 'Tors',
                'model_ar' => 'تورس',
                'image' => 'assets/images/cars/ford_tors.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['hyundai'],
                'category_id' => $categories['Popular'],
                'model_en' => 'Van H1',
                'model_ar' => 'فان إتش وان',
                'image' => 'assets/images/cars/h1.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['hyundai'],
                'category_id' => $categories['VIP'],
                'model_en' => 'Staria',
                'model_ar' => 'ستاريا',
                'image' => 'assets/images/cars/staria.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['gmc'],
                'category_id' => $categories['Popular'],
                'model_en' => 'Yukon 2020',
                'model_ar' => 'يوكن 2020',
                'image' => 'assets/images/cars/gmc-2020.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['gmc'],
                'category_id' => $categories['VIP'],
                'model_en' => 'Yukon 2023',
                'model_ar' => 'يوكن 2023',
                'image' => 'assets/images/cars/gmc-2023.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['toyota'],
                'category_id' => $categories['Group'],
                'model_en' => 'Hiace',
                'model_ar' => 'هايس',
                'image' => 'assets/images/cars/hiace.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['toyota'],
                'category_id' => $categories['Group'],
                'model_en' => 'Coaster',
                'model_ar' => 'كوستر',
                'image' => 'assets/images/cars/coaster.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
            [
                'brand_id' => $brands['mercedes'],
                'category_id' => $categories['Group'],
                'model_en' => 'Bus',
                'model_ar' => 'أتوبيس',
                'image' => 'assets/images/cars/bus.png',
                'is_active' => 1,
                'is_available' => 1,
                'reduce' => 0,
                'stars' => 5,
            ],
        ];
        // $cars = [
        //     [
        //         'brand' => 'Toyota',
        //         'model' => 'Camry',
        //         'engine' => '2.5L',
        //         'price_per_day' => 50,
        //         'image' => 'assets/images/cars/Toyota_Camry.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',
        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Honda',
        //         'model' => 'Civic',
        //         'engine' => '1.8L',
        //         'price_per_day' => 45,
        //         'image' => 'assets/images/cars/Honda_Civic.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',
        //         'reduce' => 10,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Ford',
        //         'model' => 'Mustang',
        //         'engine' => '5.0L V8',
        //         'price_per_day' => 70,
        //         'image' => 'assets/images/cars/Ford_Mustang.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',
        //         'reduce' => 0,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'BMW',
        //         'model' => 'X5',
        //         'engine' => '3.0L',
        //         'price_per_day' => 80,
        //         'image' => 'assets/images/cars/BMW_X5.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Mercedes-Benz',
        //         'model' => 'E-Class',
        //         'engine' => '2.0L',
        //         'price_per_day' => 65,
        //         'image' => 'assets/images/cars/Mercedes-Benz_E-Class.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 10,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Chevrolet',
        //         'model' => 'Malibu',
        //         'engine' => '1.5L',
        //         'price_per_day' => 55,
        //         'image' => 'assets/images/cars/Chevrolet_Malibu.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 50,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Audi',
        //         'model' => 'A4',
        //         'engine' => '2.0L',
        //         'price_per_day' => 70, 5,
        //         'image' => 'assets/images/cars/Audi_A4.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Nissan',
        //         'model' => 'Altima',
        //         'engine' => '2.5L',
        //         'price_per_day' => 50,
        //         'image' => 'assets/images/cars/Nissan_Altima.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 60,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Hyundai',
        //         'model' => 'Sonata',
        //         'engine' => '2.5L',
        //         'price_per_day' => 45,
        //         'image' => 'assets/images/cars/Hyundai_Sonata.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Kia',
        //         'model' => 'Optima',
        //         'engine' => '2.0L',
        //         'price_per_day' => 45,
        //         'image' => 'assets/images/cars/Kia_Optima.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Volkswagen',
        //         'model' => 'Golf',
        //         'engine' => '1.4L',
        //         'price_per_day' => 60,
        //         'image' => 'assets/images/cars/Volkswagen_Golf.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Subaru',
        //         'model' => 'Impreza',
        //         'engine' => '2.0L',
        //         'price_per_day' => 60,
        //         'image' => 'assets/images/cars/Subaru_Impreza.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Ford',
        //         'model' => 'Focus',
        //         'engine' => '1.6L',
        //         'price_per_day' => 50,
        //         'image' => 'assets/images/cars/Ford_Focus.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Tesla',
        //         'model' => 'Model 3',
        //         'engine' => 'Electric',
        //         'price_per_day' => 90,
        //         'image' => 'assets/images/cars/Tesla_Model_3.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Chevrolet',
        //         'model' => 'Camaro',
        //         'engine' => '6.2L V8',
        //         'price_per_day' => 100,
        //         'image' => 'assets/images/cars/Chevrolet_Camaro.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Jaguar',
        //         'model' => ' F-Type',
        //         'engine' => '3.0L V6',
        //         'price_per_day' => 120,
        //         'image' => 'assets/images/cars/Jaguar_F-Type.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 35,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Lexus',
        //         'model' => 'RX 350',
        //         'engine' => '3.5L V6',
        //         'price_per_day' => 80,
        //         'image' => 'assets/images/cars/Lexus_RX_350.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Volvo',
        //         'model' => 'XC60',
        //         'engine' => '2.0L',
        //         'price_per_day' => 70,
        //         'image' => 'assets/images/cars/Volvo_XC60.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Porsche',
        //         'model' => '911 Carrera',
        //         'engine' => '3.0L Flat-6',
        //         'price_per_day' => 150.00,
        //         'image' => 'assets/images/cars/Porsche_911_Carrera.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Mitsubishi',
        //         'model' => 'Outlander',
        //         'engine' => '2.4L',
        //         'price_per_day' => 60.00,
        //         'image' => 'assets/images/cars/Mitsubishi_Outlander.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Land Rover',
        //         'model' => 'Range Rover Sport',
        //         'engine' => '3.0L V6',
        //         'price_per_day' => 120.00,
        //         'image' => 'assets/images/cars/Land_Rover_Range_Rover_Sport.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'GMC',
        //         'model' => 'Sierra_1500',
        //         'engine' => '5.3L V8',
        //         'price_per_day' => 120.00,
        //         'image' => 'assets/images/cars/GMC_Sierra_1500.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 35,
        //         'stars' => 4,
        //     ],
        //     [
        //         'brand' => 'Fiat',
        //         'model' => '500',
        //         'engine' => '1.4L',
        //         'price_per_day' => 40.00,
        //         'image' => 'assets/images/cars/Fiat_500.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Mini',
        //         'model' => 'Cooper',
        //         'engine' => '1.5L',
        //         'price_per_day' => 55.00,
        //         'image' => 'assets/images/cars/Mini_Cooper.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',
        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Audi',
        //         'model' => 'Q5',
        //         'engine' => '2.0L',
        //         'price_per_day' => 80.00,
        //         'image' => 'assets/images/cars/Audi_Q5.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ], [
        //         'brand' => 'Chevrolet',
        //         'model' => 'Tahoe',
        //         'engine' => '5.3L V8',
        //         'price_per_day' => 110.00,
        //         'image' => 'assets/images/cars/Chevrolet_Tahoe.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Ford',
        //         'model' => 'Explorer',
        //         'engine' => '3.5L V6',
        //         'price_per_day' => 95.00,
        //         'image' => 'assets/images/cars/Ford_Explorer.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 30,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Jeep',
        //         'model' => 'Wrangler',
        //         'engine' => '3.6L V6',
        //         'price_per_day' => 100.00,
        //         'image' => 'assets/images/cars/Jeep_Wrangler.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 20,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Mazda',
        //         'model' => 'CX-5',
        //         'engine' => ' 2.5L',
        //         'price_per_day' => 65.00,
        //         'image' => 'assets/images/cars/Mazda_CX-5.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 15,
        //         'stars' => 5,
        //     ],
        //     [
        //         'brand' => 'Hyundai',
        //         'model' => 'Tucson',
        //         'engine' => ' 2.0L',
        //         'price_per_day' => 50.00,
        //         'image' => 'assets/images/cars/Hyundai_Tucson.jpg',
        //         'quantity' => 1,
        //         'status' => 'Available',

        //         'reduce' => 40,
        //         'stars' => 5,
        //     ],
        // ];

        foreach ($myCars as $car) {
            Car::create($car);
        }
    }
}
